"""add count_logged_in for User Model

Revision ID: e2e31859cb17
Revises: e5140d807c56
Create Date: 2019-03-09 19:26:50.379010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e31859cb17'
down_revision = 'e5140d807c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('count_logged_in', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'count_logged_in')
    # ### end Alembic commands ###
