"""new last_logged_on added to User

Revision ID: e5140d807c56
Revises: e2b34846a1e2
Create Date: 2019-03-09 19:01:08.840655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5140d807c56'
down_revision = 'e2b34846a1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_logged_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_logged_on')
    # ### end Alembic commands ###
